global:
  image:
    tag: v2.13.0
  securityContext:
    runAsNonRoot: true
    fsGroup: 999

dex:
  enabled: true
  service:
    type: ClusterIP

redis:
  enabled: true
  auth:
    enabled: false
  # resources:
  #   requests:
  #     cpu: 50m
  #     memory: 128Mi
  #   limits:
  #     cpu: 200m
  #     memory: 256Mi
applicationController:
  clusterAdminAccess:
    enabled: true   # allow the in-cluster cluster to be managed

controller:
  # serviceAccount:
    # create: true
    # name: argocd-application-controller
    # automountServiceAccountToken: true
  clusterAdminAccess:
    enabled: true
  replicas: 1
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 256Mi
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi

repoServer:
  replicas: 1
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 256Mi
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi

server:
  replicas: 1
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.0.203
    ports:
      http: 80
      https: 443
  extraArgs:
    - --insecure
  serviceAccount:
    create: true
    name: argocd-server
    annotations: {}
    automountServiceAccountToken: true

  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 256Mi
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi




  # resources:
  #   requests:
  #     cpu: 50m
  #     memory: 128Mi
  #   limits:
  #     cpu: 200m
  #     memory: 256Mi

configs:
  params:
    create: true
    server.insecure: true
  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance
    timeout.reconciliation: 180s
  rbac:
    create: true
  
  secret:
    # Optional: override admin password (bcrypt hash)
    # You can generate this with: htpasswd -nbBC 10 "" "mypassword" | tr -d ':\n'
    argocdServerAdminPassword: "$2y$10$nykrgqeG8LK9lF3sfww34uItwvc8Oz29DRaolWahzEOBSy7y3VEN2"
  clusters:
    - name: default
      server: https://kubernetes.default.svc
      config:
  repositories:
    kubernetesops:
      type: git
      name: kubernetesops
      url: https://github.com/KingRiq/KubernetesOps.git
    coreapplications:
      type: git
      name: coreapplications
      url: https://github.com/KingRiq/CoreApplications.git
      username: KingRiq
      password: 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



  # # Repositories (credentialTemplates make these reusable)
  # credentialTemplates:
  #   github-creds:
  #     url: https://github.com/YourUser/KubernetesOps.git
  #     username: "YourUser"
  #     password: "ghp_yourPersonalAccessToken"

  # # Optional: inline repository definitions (for private repos)
  # repositories:
  #   kubernetesops:
  #     url: https://github.com/YourUser/KubernetesOps.git
  #     type: git
  #     name: kubernetesops
  #     passwordSecret:
  #       name: argocd-secret
  #       key: githubToken

  # # Optional: Cluster credentials
  # clusters:
  #   mycluster:
  #     server: "https://192.168.0.100:6443"
  #     name: "rke2"
  #     config:
  #       bearerToken: "REDACTED_TOKEN"
  #       tlsClientConfig:
  #         insecure: false
  #         caData: "BASE64_CA_CERT"

applicationSet:
  enabled: true

notifications:
  enabled: true





