apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio-forward
  namespace: istio-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "*.chaoscauldron.space"
    secretName: galaxia-tls
  rules:
  - host: "*.chaoscauldron.space"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: istio-ingress
            port:
              number: 80
