nfs_namespace: storage
nfs_server_ip: 192.168.0.222
nfs_export_path: "{{ storage_host_path }}"
nfs_provisioner_name: nfs-client-provisioner
storage_classes:
  - name: nfs-rwx
  - name: nfs-rwo
  - name: nfs-rox
  - name: external-host

additional_mount: ""
additional_volumes: ""